runtime: php80
api_version: 1
handlers:
- url: /
  script: index.php
# Serve images as static resources.
- url: /(.+\.(gif|png|jpg))$
  static_files: \1
  upload: .+\.(gif|png|jpg)$
# Serve php scripts.
- url: /(.+\.php)$
  script: \1
